### ISSUE TITLE
Orders setting page

### ISSUE THREAD

**Issue by BALAJIRAGUNATHAN** [benitto-flycart/review-plugin#119]
1.  When clicking the send now button it shows (Server Error Occurred)

[Screencast from 2024-11-22 15-57-47.webm](https://github.com/user-attachments/assets/b718845b-e664-4631-8da9-f720f6ef0e95)

**Comment by benitto-flycart** [comment]
https://github.com/benitto-flycart/review-plugin/issues/116 - Duplicate issue.

**Comment by BALAJIRAGUNATHAN** [comment]
Issue fixed 

[Screencast from 2024-11-25 10-42-16.webm](https://github.com/user-attachments/assets/36a3118b-f8df-45a4-a484-17328447a0c1)
