### ISSUE TITLE
Rating Review Widget

### ISSUE THREAD

**Issue by BALAJIRAGUNATHAN** [benitto-flycart/review-plugin#24]
1. update the latest (ADD to Cart) Icon

![image](https://github.com/user-attachments/assets/d5c709a4-301d-4be6-97d0-3e88debe25c3)

**Comment by BALAJIRAGUNATHAN** [comment]
not showing on shop page

**Comment by benitto-flycart** [comment]
@BALAJIRAGUNATHAN  The point one is invalid

**Comment by BALAJIRAGUNATHAN** [comment]
resolved
