### ISSUE TITLE
Review Reminder

### ISSUE THREAD

**Issue by BALAJIRAGUNATHAN** [benitto-flycart/review-plugin#34]
- [ ] https://github.com/benitto-flycart/review-plugin/issues/34#issuecomment-2425599870
- [ ] https://github.com/benitto-flycart/review-plugin/issues/34#issuecomment-2425603448

1. Remove the notes section and make sure that section is in an automatic way

![screenshot-site1_local-2024_10_21-10_34_25](https://github.com/user-attachments/assets/91150eb7-242c-4fff-96af-ffc2382cf7d4)

**Comment by BALAJIRAGUNATHAN** [comment]
2. Add the emoji Texts for this Button Text

![screenshot-site1_local-2024_10_21-10_37_22](https://github.com/user-attachments/assets/2ad860b5-c62e-478a-9dfd-da7e31395afb)

**Comment by BALAJIRAGUNATHAN** [comment]
3. make sure the Preview option is in desktop and mobile view.


![screenshot-site1_local-2024_10_21-10_40_30](https://github.com/user-attachments/assets/9e06efd4-ec5c-454e-8eea-ccb9077fddba)

**Comment by benitto-flycart** [comment]
@BALAJIRAGUNATHAN The point one is invalid

**Comment by BALAJIRAGUNATHAN** [comment]
Issue Fixed

2. 
![screenshot-site1_local-2024_10_28-10_52_31](https://github.com/user-attachments/assets/d69a7a84-bcf8-412a-9671-02f224e90959)

3
![screenshot-site1_local-2024_10_28-10_53_04](https://github.com/user-attachments/assets/03519f4e-8eaa-45ca-816c-5b815533083b)
