### ISSUE TITLE
make sure the Preview option is in desktop and mobile view.

### ISSUE THREAD

**Issue by benitto-flycart** [benitto-flycart/review-plugin#41]
make sure the Preview option is in desktop and mobile view.

![screenshot-site1_local-2024_10_21-10_40_30](https://github.com/user-attachments/assets/9e06efd4-ec5c-454e-8eea-ccb9077fddba)

_Originally posted by @BALAJIRAGUNATHAN in https://github.com/benitto-flycart/review-plugin/issues/34#issuecomment-2425603448_

**Comment by BALAJIRAGUNATHAN** [comment]
Issue Fixed 

![screenshot-site1_local-2024_10_28-10_40_35](https://github.com/user-attachments/assets/88025edc-92e6-40cd-8929-44a3d3c7aed4)
