### ISSUE TITLE
Popup Widget

### ISSUE THREAD

**Issue by BALAJIRAGUNATHAN** [benitto-flycart/review-plugin#64]
1. remove the Auto Play Video Review

![screenshot-site1_local-2024_11_05-10_56_21](https://github.com/user-attachments/assets/d3ca9497-9f3e-4437-83d0-edc3ffc05061)

**Comment by BALAJIRAGUNATHAN** [comment]
2. Hide on mobile option is not working

![screenshot-site1_local-2024_11_05-10_59_06](https://github.com/user-attachments/assets/82b3d8f3-f7cc-49a3-aa69-8b1fda211f04)

**Comment by benitto-flycart** [comment]
Issue 1 is fixed and issue two is created as separated due to it's low priority.
